version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cardgame-postgres
    environment:
      POSTGRES_DB: cardgame
      POSTGRES_USER: cardgame_user
      POSTGRES_PASSWORD: cardgame_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cardgame_user -d cardgame"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cardgame-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
